### ISSUE TITLE
Throws unclear error message when NetLogo is not allowed to use Camera on macOS

### ISSUE THREAD

**Issue by LaCuneta** [NetLogo/Vid-Extension#30]
On trying to open the camera with `vid:camera-select` (or others) with the new JavaCV library without proper Camera access in the Security and Privacy of the system on macOS, the below exception will be thrown.  Ideally we'd want to prompt macOS users to allow Camera access using a macOS system dialog.  But if that isn't possible, at least alerting them to the proper issue would be more helpful.

Here is how to check and make sure NetLogo is allowed to access the Camera in the macOS Security and Privacy settings:  https://support.apple.com/en-ph/guide/mac-help/mchlf6d108da/mac  

```
org.bytedeco.javacv.FrameGrabber$Exception: read() Error: Could not read frame in start().
 at org.bytedeco.javacv.OpenCVFrameGrabber.start(OpenCVFrameGrabber.java:265)
 at org.nlogo.extensions.vid.Camera.$anonfun$grabber$1(Camera.scala:71)
 at org.nlogo.extensions.vid.Camera$.withContextClassLoader(Camera.scala:31)
 at org.nlogo.extensions.vid.Camera.<init>(Camera.scala:69)
 at org.nlogo.extensions.vid.Camera$.open(Camera.scala:62)
 at org.nlogo.extensions.vid.CameraSelect.$anonfun$perform$1(CameraSelect.scala:13)
 at org.nlogo.extensions.vid.CameraSelect.$anonfun$perform$1$adapted(CameraSelect.scala:12)
```

**Comment by LaCuneta** [comment]
Added more info on what to do with a pop-up message in [this commit](https://github.com/NetLogo/Vid-Extension/commit/5b1a756e79fa46a63a0cbbd06102f1e3e3c22d61)
